---
functional:
  - Сайт должен иметь возможность авторизации через GitHub
  - Сайт должен обеспечивать возможность соревнований между двумя пользователями в решении задач
  - Сайт должен поддерживать игру с ботом различной сложности
  - Сайт должен отображать рейтинги пользователей
  - Сайт должен позволять пользователям делиться ссылками для игры с друзьями
  - Сайт должен предоставлять возможность создавать и участвовать в турнирах
  - Пользователям должна быть предоставлена задача, которую нужно решить на выбранном языке программирования
  - Пользователи должны иметь возможность общаться с соперником и зрителями в чате
  
non-functional:
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - Сайт должен быть доступен круглосуточно, за исключением необходимых технических работ, о которых пользователи должны быть уведомлены заранее.
  - Сайт должен быть доступен на нескольких языках для международной аудитории (как минимум русский и английский)
  - Сайт должен иметь документацию, поддерживаемую сообществом, и быть доступной для новых участников проекта
